name: Rust

on: 
  workflow_dispatch:
  push:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.lock'
      - '**.yml'
  
env:
  BIN_PATH: target/lambda
  BIN_NAME: bootstrap

jobs:

  checkout-repository:

    runs-on: self-hosted
    steps:
      - name: print event info
        run: echo '${{ toJSON(github.event) }}'
        
      - name: Checkout Repo
        uses: actions/checkout@v3

  build-lambdas:
    env:
      CLEANER: cloud_bucket_cleaner
      MAIN: cloud_main_lambda
      GENERATOR: cloud_generator_lambda
      
    runs-on: self-hosted
    needs: checkout-repository
    
    steps:
    - name: Build Lambda
      run: echo "henlo" #cargo lambda build --release;

  upload-artifacts:
    
    needs: build-lambdas
    runs-on: self-hosted
    steps:
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lambda-binaries
        path: 'target/lambda/**'
  
  download-artifacts:
    runs-on: self-hosted
    needs: upload-artifacts
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3 # not specifying which artifact downloads all artifacts
    - name: List directory
      run: ls -R
