name: Rust

on: 
  workflow_dispatch:
  push:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.lock'
      - '**.yml'
  
env:
  TF_VAR_TABLE_NAME: "cloud-wave-file" 
  TF_VAR_GLOBAL_INDEX: "cloud-date-time-index"
  TF_VAR_BUCKET_NAME: "cloud-wave-file-bucket"
  TF_VAR_GENERATOR_LAMBDA: "cloud-sine-generator"
  TF_VAR_CLEANER_LAMBDA: "cloud-bucket-cleaner"
  TF_VAR_MAIN_LAMBDA: "cloud-main"

jobs:

  checkout-repository:

    runs-on: self-hosted
    steps:
      - name: print event info
        run: echo '${{ toJSON(github.event) }}'
        
      - name: Checkout Repo
        uses: actions/checkout@v3
  
  build-lambdas:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo lambda build --release
      
  upload-artifacts:
    env:
      BIN_PATH: "target/lambda"
      BIN_NAME: "bootstrap.zip"
      
    needs: build-lambdas
    runs-on: self-hosted
    
    steps:
    - name: Zip Bootstrap Binaries
      run: |
        zip $BIN_PATH/cloud-main/bootstrap.zip target/lambda/cloud-main/bootstrap
        zip target/lambda/cloud-bucket-cleaner/bootstrap.zip target/lambda/cloud-bucket-cleaner/bootstrap
        zip target/lambda/cloud-sine-generator/bootstrap.zip target/lambda/cloud-sine-generator/bootstrap
  
  download-artifacts:
    runs-on: self-hosted
    needs: upload-artifacts
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3 # not specifying which artifact downloads all artifacts
    - name: List directory
      run: ls -R
